version: "3"
services:
  express:
    build: ./express
    container_name: express
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./express:/express
      - /express/node_modules
    depends_on:
      mosquitto:
        condition: service_started
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log